### ISSUE TITLE
Make sure all tests conform to the recommended maven structure

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#11]

**Comment by ShaiZeevi** [comment]
Done

**Comment by yossigil** [comment]
all tests must be in the test hierarchy

**Comment by yossigil** [comment]
e.g., class UTIL has its own internal TEST class

**Comment by yossigil** [comment]
@ShaiZeevi

**Comment by ShaiZeevi** [comment]
> e.g., class UTIL has its own internal TEST class

We operated according to this comment

**Comment by yossigil** [comment]
this is not the recommended maven structure. please assign someone to this issue

**Comment by yossigil** [comment]
why was this closed?

**Comment by yossigil** [comment]
add a ref duplicate of #something

**Comment by yossigil** [comment]
no it is not, see e.g., class prune. there are a couple of others.

**Comment by yossigil** [comment]
to close inclue a screen dump showing that running the source folders as junit tests does not produce any tests

**Comment by ofiralexi** [comment]
Will do once I'm done.

**Comment by ofiralexi** [comment]
Attaching proof from the IDE :
![image](https://user-images.githubusercontent.com/37834992/48257822-499c5700-e41c-11e8-83b9-b604b457fe95.png)

![image](https://user-images.githubusercontent.com/37834992/48257812-43a67600-e41c-11e8-9cc3-bd232f4ac5c5.png)

If more proof neccessary, say so @yossigil

**Comment by yoavz1997** [comment]
@YarinSh

**Comment by ShaiZeevi** [comment]
Seems good, closing
