### ISSUE TITLE
Unit Tests to has.java

### ISSUE THREAD

**Issue by yoavz1997** [TechnionYP5779/team1#113]

**Comment by ShaiZeevi** [comment]
reviewing

**Comment by ShaiZeevi** [comment]
Please fix the uses of assert instead of azzert:
![image](https://user-images.githubusercontent.com/36810747/48559440-575a4c80-e8f4-11e8-8b49-0b98dad76461.png)

**Comment by yoavz1997** [comment]
@ShaiZeevi please look at the comments of #62

**Comment by ShaiZeevi** [comment]
Ok then, approved!
