### ISSUE TITLE
Unit Tests Outer.java

### ISSUE THREAD

**Issue by yoavz1997** [TechnionYP5779/team1#123]
#96

**Comment by ofiralexi** [comment]
Can;'t clone outer

**Comment by yoavz1997** [comment]
Even so, there are still more branches to explore such as new Outer<>(null) which throws an exception.
It can be tested by using
@Test(expected = IllegalArgumentException.class) public void test() {...}

**Comment by ShaiZeevi** [comment]
@ofiralexi I see there has been a commit since the last review. Are you submitting the tests for a re-review? They are currently rejected

**Comment by ofiralexi** [comment]
@ShaiZeevi I am missing one equals branch, and I can't seem to figure out which one. 
If you have any idea, it will be of help :)

**Comment by yoavz1997** [comment]
Done #79
