### ISSUE TITLE
add some more descriptive stuff in your readme.md file

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#129]
_From @yossigil on November 8, 2018 17:37_

remember this is how people will see you project on the web

_Copied from original issue: TechnionYP5779/team6#64_

**Comment by saifun** [comment]
Think I'm finished :)

**Comment by Matanpugach** [comment]
Nicely done! Great job Saifun! 😄 Hope we'll get the lgtm running again 😞 #79
