### ISSUE TITLE
use fluent style of assertions

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#130]
azzert.assertEquals(the.sqr(0), 0);
    azzert.assertEquals(the.sqr(3), 9);
    azzert.assertEquals(the.sqr(2), 4);
    azzert.assertEquals(the.sqr(1), 1);
    
    i.e., is(0)

**Comment by ShaiZeevi** [comment]
@saifun @ofiralexi @yoavz1997 @Matanpugach @YarinSh @Itamaror 
I think it's too much work for a single person. How about we divide it so that we each fix the tests we wrote?

**Comment by ShaiZeevi** [comment]
Everyone, I believe the required style is something like this:
![image](https://user-images.githubusercontent.com/36810747/48610880-f41cf880-e98d-11e8-9f90-baffab764907.png)

@yossigil is this ok?

**Comment by ofiralexi** [comment]
@ShaiZeevi yes in case of true and false, you should rewrite it as:
assert SomeStatementThatIsTrue
referencing the relevant issue for you #90

**Comment by yoavz1997** [comment]
Done #79
