### ISSUE TITLE
Document the new updated code conventions in the wiki

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1#138]
Due to recent claims that the convention should be written down

**Comment by ShaiZeevi** [comment]
@Matanpugach @yoavz1997 @YarinSh @saifun @ofiralexi @Itamaror 
The page is up in the sidebar and details rules and guidelines for various aspects of working on the project. It was very articulately written by yours truly and since we need to agree on our etiquette I want everyone to read and understand the document. If you have a problem with this initial document please reply here

**Comment by Matanpugach** [comment]
I will add more info regarding unit-testing.

**Comment by yossigil** [comment]
can you provide a link

**Comment by Matanpugach** [comment]
[here](https://github.com/TechnionYP5779/team1/wiki/Project-Rules-and-Guidelines)

**Comment by yoavz1997** [comment]
Ofir and I approve

**Comment by saifun** [comment]
I read, agree, and undertake to act according to what is written in the document 😁 
Good luck! And a really great job @ShaiZeevi

**Comment by ofiralexi** [comment]
@Itamaror @YarinSh If you have both read it, we can close this issue

**Comment by YarinSh** [comment]
I read it and approve it.

**Comment by Itamaror** [comment]
Read and approved!
Closing.
