### ISSUE TITLE
polish your code: change box.box(x) to box.it(x), or to box(x); same with unbox

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#141]

**Comment by ShaiZeevi** [comment]
I did the previous refactoring so I guess I'll take this one

**Comment by ofiralexi** [comment]
This is a duplicate issue of #80 , as you mentioned so open the old one

**Comment by yossigil** [comment]
not, it is not... but you can still open the old one.
refactoring was done, all you need is polish it now

**Comment by ShaiZeevi** [comment]
I would rather have this one open than the old one since it has a clearer title. I'm putting everything back to the way it was

**Comment by ShaiZeevi** [comment]
![image](https://user-images.githubusercontent.com/36810747/48732370-28234280-ec48-11e8-971a-c8d347226c50.png)
All code is cleansed of box.box, I'm moving on to unbox.unbox

**Comment by ShaiZeevi** [comment]
![image](https://user-images.githubusercontent.com/36810747/48733207-8ea96000-ec4a-11e8-9180-a857fafa9f95.png)
![image](https://user-images.githubusercontent.com/36810747/48733222-a08b0300-ec4a-11e8-9bb6-b17962463337.png)
Done!
Also, I'm adding this to the boxing section of the code conventions wiki page

**Comment by YarinSh** [comment]
Looks good! Closing #79
