### ISSUE TITLE
factor out @SuppressWarnings("unused"), if applies to many methods in class, e.g., in forget

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#143]

**Comment by yoavz1997** [comment]
There shouldn't be any because of #88

**Comment by yoavz1997** [comment]
I stand corrected, are is one in lazy and one in PropositionPrettyPrinter
The last one is in forget

**Comment by Itamaror** [comment]
Not really sure what was expected to be done, but i removed some of the @SuppressWarnings("unused") in the code.

**Comment by yoavz1997** [comment]
There are only 2 uses which are necessary #79
