### ISSUE TITLE
Document Class list

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1#146]

**Comment by Matanpugach** [comment]
Reviewing now

**Comment by Matanpugach** [comment]
I have a few points to consider:
1. I have noticed you documented classes and functions in the main class and sub-classes using a block comment, while functions in the sub-classes were documented with a row comment. Personally, i think it will be more aesthetic if you already chose to document (externally, where the declaration is) in a uniform way (such as, using a block comment). 
2. Regarding the uniformity of the documentation:
![image](https://user-images.githubusercontent.com/27849930/48786920-7855df80-ecf0-11e8-8538-402651a1471d.png)
Using a regular template with the same inner-order will be best 
3. Please make sure all of sentences start with a capital letter
![image](https://user-images.githubusercontent.com/27849930/48787047-b7843080-ecf0-11e8-80c0-b2a6fe43525a.png)

**Comment by ShaiZeevi** [comment]
@Matanpugach thank you for the great feedback, I fixed all the issues you mentioned.
Would love it you could re-review it at your earliest convenience.

**Comment by Matanpugach** [comment]
You did a good job! closing #79
