### ISSUE TITLE
Polish your code: Utils.cantBeNull(x) -> cantBeNull(x)

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#150]

**Comment by YarinSh** [comment]
Did it for Utils.cantBeNull:
![image](https://user-images.githubusercontent.com/32907017/48736526-2fe8e400-ec54-11e8-8133-277f40b7c7aa.png)
Should I do the same for Utils.canBeNull, i.e, turn it to canBeNull?

**Comment by yoavz1997** [comment]
There are more "Utils.canBeNull" to handle

**Comment by YarinSh** [comment]
Ok removed Utils.canBeNull as well now - 
![image](https://user-images.githubusercontent.com/32907017/48786316-4a23d000-ecef-11e8-91c6-9c1bc0835bb4.png)

**Comment by Itamaror** [comment]
Great Job! #79
