### ISSUE TITLE
make sure that nulling and forget are in fluent.ly

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#151]

**Comment by YarinSh** [comment]
Build failed in TRAVIS CI and forget and nulling cannot be resolved.

**Comment by ofiralexi** [comment]
![image](https://user-images.githubusercontent.com/37834992/48736793-f06ec780-ec54-11e8-80bf-e778fb782ee6.png)
This is failing due to merging gone wrong

**Comment by Itamaror** [comment]
Fixed

**Comment by Itamaror** [comment]
Not fixed, my bad.

**Comment by Itamaror** [comment]
Ok now it fixed.

**Comment by YarinSh** [comment]
Just one more thing - the nullingTest.java should move to it's correct place as well.

**Comment by Itamaror** [comment]
Nice Catch!

**Comment by ofiralexi** [comment]
Issue #79 
Good job ! closing
![image](https://user-images.githubusercontent.com/37834992/48773865-497c4100-ecd1-11e8-9e88-0e5ce9945636.png)
![image](https://user-images.githubusercontent.com/37834992/48773872-4e40f500-ecd1-11e8-9d7a-324ec18192a7.png)
