### ISSUE TITLE
class zero is for snippets such as return zero.forget(x). Make sure this class and other fluent classes like this e.g., de.fault, are in fluent.ly

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#152]

**Comment by ofiralexi** [comment]
They are already in fluent.ly
![image](https://user-images.githubusercontent.com/37834992/48773628-a1ff0e80-ecd0-11e8-86d1-069b549b0528.png)
![image](https://user-images.githubusercontent.com/37834992/48773638-aa574980-ecd0-11e8-82e3-1ca3d3d47c8a.png)

I couldn't detect other classes as short and forget as this one that aren't in fluent.ly.
Let's see if anyone else has an idea

**Comment by Matanpugach** [comment]
Reviewing now

**Comment by saifun** [comment]
I agree.
I looked over all the packages and everything looks in the right place :)
Closing the issue
