### ISSUE TITLE
Polish: convert azzert.that(the.max(1, 3, 2), azzert.is(3)) to  azzert.that(the.max(1, 3, 2), is(3)) [hint: search for ", azzert.is("

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#153]

**Comment by yoavz1997** [comment]
![image](https://user-images.githubusercontent.com/33288016/48779192-b8f92d00-ecdf-11e8-940d-3815b4cc1b7e.png)
It seems that the whole code is polished

**Comment by Matanpugach** [comment]
reviewing now

**Comment by Matanpugach** [comment]
Well Done, Yoav! #79
