### ISSUE TITLE
Update github to upcoming sprint

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1#166]
Due to what was decided on in the last team meeting, there's a need to update the github ( sprints, wiki etc... ) on the relevant stuff for the upcoming sprints.

**Comment by ofiralexi** [comment]
Updated wiki page with all starting information needed: [wiki-TechnoBotSprint]
please all read and share your thoughts so we can start the upcoming short sprint.
@yoavz1997 @ShaiZeevi @saifun @Itamaror @YarinSh @Matanpugach 

 [wiki-TechnoBotSprint]: (https://github.com/TechnionYP5779/team1/wiki/Bot---Test-Sprint)

**Comment by Matanpugach** [comment]
Great! I uploaded and ordered the meeting summary, Parking Spots Management idea development and work division.

**Comment by ofiralexi** [comment]
Okay, added it to the sidebar. Please make sure to do it yourself in future times :) @Matanpugach

**Comment by Matanpugach** [comment]
@ofiralexi It is on the side bar (under week #5 meeting) and here:
![image](https://user-images.githubusercontent.com/27849930/48840370-14d2bd00-ed97-11e8-8d08-0a6ce19f0854.png)
If you think now there is a duplication, let me know 😸
