### ISSUE TITLE
Extract data of opening hours of Technions businesses

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1#170]
Description: Extract the information of the opening hours of the Technion businesses into a CSV.
The CSV should include:
business name, working hours on Sunday, working hours on Monday, ...

I believe most of the businesses are mentioned here: http://www.asat.org.il/eng/asakim
If you have information about any other business, please inform.

**Comment by yoavz1997** [comment]
There are plenty more which do nit appear on that site such as thw gym and the pool. The wiki has some more links, but I'll look for more.

**Comment by ofiralexi** [comment]
If Google recognize those businesses can be done using Google API: https://developers.google.com/places/web-service/details?fbclid=IwAR2tDsPfzbP4PARTOU7jdv2R6taMr4sHUi1kw524QyQoJ42JiEYKCf4kFvM

**Comment by ofiralexi** [comment]
brilliant! closing #79
