### ISSUE TITLE
Update parking DB fields

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1#188]
Description: In the wiki under 
![image](https://user-images.githubusercontent.com/37834992/49147624-d779ac80-f30d-11e8-9008-2bc451e4f329.png)
There is a description of the different tables of the project. Please give more information about the columns. For example names, constraints.

**Comment by yoavz1997** [comment]
Note that in the current sprint a parking spot is purchased so there is no need for the Transaction table and in the Parking table another column with the new owner is added to indicate that the parking spot is taken.
This corresponds to #193

**Comment by yoavz1997** [comment]
Fixed the wiki page https://github.com/TechnionYP5779/team1/wiki/Parking-Space-Management-Idea

**Comment by ofiralexi** [comment]
@yoavz1997 you mentioned that for the current sprint there is no need in transaction table. However there is one in the wiki page. So do we have a transaction table or not ?

**Comment by yoavz1997** [comment]
The scheme in the wiki page is the official one, for the entire project. On the current sprint, the layout will not include the Transaction table, and an "owner" column will be added to the Parking Spot table (which will be a foreign key from the User table) to indicate by whom (if any) the parking was purchased.

**Comment by ofiralexi** [comment]
Interesting. I believe that this scheme should be more extended for more complicated features (filtering by shadow, soil, rank and reviews etc... ). But they do not conceren this sprint, where the current schema does sufficient , and it is probably best discussed in the next team meeting for next sprints . Closing #79
