### ISSUE TITLE
Offer new parking spot

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1#192]
Description: the user should be able to offer a new parking spot for other users to order.

**Comment by YarinSh** [comment]
Which technology you guys want to use for the server-side scripting (Sending the data inputted to the database) PHP or Node.js?

**Comment by yoavz1997** [comment]
If think for now, maybe just using JavaScript for the server side as well could be an idea since we are trying to abort this project.

**Comment by YarinSh** [comment]
Ok tried to use the ACCESSDB library but it does not seem to work, so Javascript is not usable to do the sever-side scripting, hence I used PHP as it is less complex.

To run the website  XAMPP needs to be installed, and the Apache and MySQL server enabled in its control panel. Also the website files need to be in the htdocs folder in the XAMPP directory.
More on this [here](https://www.codeofaninja.com/2013/06/how-to-run-a-php-script.html).

The parking spot table:
`CREATE TABLE parkingspots (
 id int(11) NOT NULL AUTO_INCREMENT,
 username varchar(20) COLLATE utf8_unicode_ci NOT NULL,
 location varchar(500) COLLATE utf8_unicode_ci NOT NULL,
 priceint(11) NOT NULL,
 PRIMARY KEY (id),
 KEY username (username),
 CONSTRAINT parkingspots_ibfk_1 FOREIGN KEY (username) REFERENCES users(username) 
ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci`

And the users temporary table:

`CREATE TABLE users (
 username varchar(20) COLLATE utf8_unicode_ci NOT NULL,
 email varchar(100) COLLATE utf8_unicode_ci NOT NULL,
 password varchar(20) COLLATE utf8_unicode_ci NOT NULL,
 PRIMARY KEY (username),
 UNIQUE KEY email(email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci`

**Comment by yoavz1997** [comment]
Why is the username in parking spots, a key?

**Comment by YarinSh** [comment]
Because it was a weird way to set up username as a foreign key in the Apache GUI, you can just use the FOREIGN KEY REFERENCES 
and of course add constraints(which I was not able to do int the GUI) accordingly on price, although the JavaScript does not allow to enter negative prices for examples.

**Comment by yoavz1997** [comment]
I meant a single user can purchase multiple parking spots and own multiple parking spots.
Moreover, I don't see the column for the username who purchased the parking spot

**Comment by YarinSh** [comment]
Yes it can still happen, a user can own multiple parking spots because the primary key is the id.

Oh, and no there is no username who purchased but can easily be added, I just did not need this column for my features, and it is not mentioned in the wiki about this columns, I though we would use Transactions for this, but I guess we can just update who bought it instead via the new column.

**Comment by yoavz1997** [comment]
As I wrote in #188  for the current sprint we do not use transactions. This column is temporary and will help you filter the unavailable parking spots, otherwise, how would you know?

**Comment by YarinSh** [comment]
Ok will add the new column and the filtering right away.

**Comment by yoavz1997** [comment]
Closed after #211 merged
