### ISSUE TITLE
Order parking spot

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1#193]
given the list of available parking spot, the user will be able to select one and order it

**Comment by yoavz1997** [comment]
In the team meeting, we said that maybe for now the order is permanent. Correct me if I'm wrong, but it seems there is no need for a designated page for ordering.

**Comment by yossigil** [comment]
change title of issue to include user story.

**Comment by ofiralexi** [comment]
@yoav1997 I believe the flow will be :
- see available parking spot
- upon click or tick or something you will be shown a message If you sure you want to order it. ( Since for this Sprint we are only supporting buying and selling )

**Comment by yoavz1997** [comment]
I see, thanks for the help!

**Comment by yoavz1997** [comment]
> change title of issue to include user story.

Could you elaborate what you mean by that? Simply to change the title to include the words "User Story" or should the format of the issue be different?

**Comment by yoavz1997** [comment]
Closed after #215 was merged
