### ISSUE TITLE
consolidate class Wrapper into Outer

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#28]

**Comment by ShaiZeevi** [comment]
Do you mean to merge the two classes?

**Comment by ofiralexi** [comment]
If so, there are some identical functions ( with different implementation ) like hash. 
In that case do we want the same behaviour for the two classes or keep it that way?

**Comment by dormaayan** [comment]
@ShaiZeevi , @ofiralexi 
Merge the classes and their behaviors

**Comment by ShaiZeevi** [comment]
Done

**Comment by yoavz1997** [comment]
@Matanpugach what do you think?

**Comment by Matanpugach** [comment]
Well done.
