### ISSUE TITLE
Move all non-general-purpose code to il.org.spartan.etc

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#30]

**Comment by ShaiZeevi** [comment]
what counts as non-general purpose code?

**Comment by dormaayan** [comment]
@ShaiZeevi I guess it means a code which is not a library of functions for general purpuse which is in use among different places...

**Comment by ShaiZeevi** [comment]
@yossigil we still don't understand what non-general purpose code means.
Could you possibly give an example of a non-general purpose class vs one that is "general purpose" + an explanation

**Comment by yossigil** [comment]
make your questions more concrete, give sample classes

**Comment by ShaiZeevi** [comment]
I guess my opinion of general purpose classes is anything that the user could directly use.
Such as - list, azzert, singleton, nil etc.
I don't have an example off the top of my head for a non-general purpose one. I was hoping you would provide me with one

**Comment by yossigil** [comment]
this are general purpose

**Comment by yoavz1997** [comment]
@ofiralexi is all non-general-purpose code in etc

**Comment by ofiralexi** [comment]
Semms fine. Closing
