### ISSUE TITLE
make sure all code is spartanized

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#37]

**Comment by ofiralexi** [comment]
To do: run spartanizer on our code

**Comment by yossigil** [comment]
it is not...

**Comment by YarinSh** [comment]
For now all code is spartanized, should I close this and mark #62 as duplicate? Or keep it open, in case more new code needs to be spartanized? @ShaiZeevi @yoavz1997 @ofiralexi @saifun @Itamaror @Matanpugach

**Comment by yossigil** [comment]
yes

**Comment by dormaayan** [comment]
@YarinSh , yes, please close the issue and make sure that the spartanizer is installed for all the team members. Please make sure to push only spartanized code

**Comment by Matanpugach** [comment]
@ShaiZeevi @yoavz1997 @ofiralexi @saifun @Itamaror Did you all install the spartanizer plugin?

**Comment by ShaiZeevi** [comment]
I’ll get to it tomorrow. I’ll appreciate it if someone could comment below some “how-to” information.

**Comment by saifun** [comment]
This is the link:
https://github.com/SpartanRefactoring/Main/wiki/Installation-Instructions

**Comment by Itamaror** [comment]
I have it installed

**Comment by ofiralexi** [comment]
I have it installed

**Comment by Matanpugach** [comment]
And i know @yoavz1997 has it too. @ShaiZeevi if you installed it please close this issue.

**Comment by ShaiZeevi** [comment]
@Matanpugach
Not yet, will ASAP and then I’ll close

**Comment by ShaiZeevi** [comment]
Installed

**Comment by yossigil** [comment]
you must be kidding...

Compliance	JRE Compiler Compliance Problem
Tip: Convert post-increment of i to pre-increment	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 106	Idiomatic
Tip: Convert post-increment of i to pre-increment	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 113	Idiomatic
Tip: Inline local list into subsequent statement	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 10	Inlining
Tip: Inline local list into subsequent statement	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 15	Inlining
Tip: Remove redundant curly braces	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 106	SyntacticBaggage
Tip: Rename iteration variable 'i' to '¢'	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 106	Centification
Tip: Rewrite 'azzert.assertTrue(false)' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 59	Idiomatic
Tip: Rewrite 'azzert.assertTrue(false)' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 72	Idiomatic
Tip: Rewrite 'azzert.assertTrue(false)' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 81	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getFirst().first.equals(Double.valueOf(1.3)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 35	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getFirst().first.equals(Double.valueOf(1.3)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 49	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getFirst().first.equals(Double.valueOf(3.5)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 68	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getFirst().second.equals(Double.valueOf(22.2)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 36	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getNext().first.equals(Double.valueOf(1.7)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 51	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getNext().first.equals(Double.valueOf(12.88)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 55	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getNext().first.equals(Double.valueOf(3.5)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 52	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getNext().first.equals(Double.valueOf(4.2)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 53	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getNext().first.equals(Double.valueOf(41.30)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 56	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getNext().first.equals(Double.valueOf(8.9)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 54	Idiomatic
Tip: Rewrite 'azzert.assertTrue(list.getNext().first.equals(Double.valueOf(93.5)))' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 57	Idiomatic
Tip: Rewrite 'azzert.assertTrue(p.first == xVals[i])' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 111	Idiomatic
Tip: Rewrite 'azzert.assertTrue(p.first >= 1.3 && p.first <= 93.5)' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 97	Idiomatic
Tip: Rewrite 'azzert.assertTrue(p.second == yVals[i])' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 112	Idiomatic
Tip: Rewrite 'azzert.assertTrue(p.second >= 2.5 && p.second <= 22.2)' as assert command	RealNumbersPairListTest.java	/fluent.ly.1/src/test/java/il/org/spartan/utils	line 98	Idiomatic

**Comment by yossigil** [comment]
please do not close issues too quickly

**Comment by yoavz1997** [comment]
It seems to be fixed now.
We apparently had some issues with the spartanizer, but they are resolved.
Now there are no warnings or tips

**Comment by yoavz1997** [comment]
![image](https://user-images.githubusercontent.com/33288016/48463261-28ed4c00-e7e4-11e8-9b2c-7555d8abd437.png)

**Comment by ShaiZeevi** [comment]
What was the eventual conclusion regarding when the Spartanizer tips to change azzert to assert?
@ofiralexi I believe you had a similar issue
