### ISSUE TITLE
make sure there are no warnings in code

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#38]

**Comment by yossigil** [comment]
how come there are still warnings?

**Comment by ofiralexi** [comment]
Three is a warning regarding a commit you've made 
![image](https://user-images.githubusercontent.com/37834992/48154548-8f003d80-e2d1-11e8-8546-3abd490d4101.png)
We get Unknown reference nature: il.org.spartan.nature
![image](https://user-images.githubusercontent.com/37834992/48154559-958eb500-e2d1-11e8-9d73-fe99660f7e14.png)
@yossigil what should we do with that?

**Comment by yossigil** [comment]
you were supposed to enable the spartanizer
