### ISSUE TITLE
Fix idiomaticTest

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1#39]

**Comment by yossigil** [comment]
please add a description of what was there to fix, and how you fixed it

**Comment by ShaiZeevi** [comment]
The problem: when idiomatic.katching catches an Exception it automatically prints out the stack trace. Resulting in a scary looking (yet passing) test - that checks the behavior of katching (to make sure all exception types are handled)

The fix: To my dismay, I commented out the test to avoid the scary message.

**Comment by yossigil** [comment]
remove the printout in the tested class; it is a design error; fix design accordingly

**Comment by yoavz1997** [comment]
@yoavz1997 Is this fine?

**Comment by yoavz1997** [comment]
![image](https://user-images.githubusercontent.com/33288016/48473976-3b767e00-e802-11e8-9ed1-cceeea14dbb4.png)
katching does not print anymore
