### ISSUE TITLE
Summarize team meeting 11/7

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1#42]

**Comment by ShaiZeevi** [comment]
Done. 
@ofiralexi @yoavz1997 @Matanpugach @saifun @YarinSh @Itamaror
Please review at your earliest convenience

**Comment by yossigil** [comment]
please include a link to the wiki page

**Comment by Matanpugach** [comment]
@yossigil Shai's wiki link
https://github.com/TechnionYP5779/team1/wiki/Third-Team-Meeting---11-7
