### ISSUE TITLE
use tdd to develop a fluent api that represents an arithemtical progression over BigInteger

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#45]
See #44 on how to define the fluent API.
Add checkboxes as necessary, note that default first value is zero, default step should e zero, and default count is infinity

**Comment by yoavz1997** [comment]
I don't see a BigInteger class in the project other than java.math
If you do mean this class, which of its functions should I implement?

**Comment by yoavz1997** [comment]
I couldn't find in the original BigInteger a function named "count".
Could you elaborate on its functionality?

**Comment by yoavz1997** [comment]
@ShaiZeevi is it done?

**Comment by ShaiZeevi** [comment]
Looking Gouda
