### ISSUE TITLE
Use tdd to develop representing recangles in the plane defined by two corner points.

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#46]
see #44, see #45 

- [x] ctors
- [x] getLen + getWidth
- [x] perimeter function
- [x] area function
- [x] rotation

**Comment by yossigil** [comment]
- [ ] use commit comment close an issue.
- [ ] place in the right package, not TDD

**Comment by yossigil** [comment]
`	  @SuppressWarnings("serial") public class IllegalParameters extends Exception {
    //for when the points actually create a line or a point
  }`

do not create your own classes; java has classes for illegal argument exception

**Comment by ShaiZeevi** [comment]
I deleted the exception

**Comment by yoavz1997** [comment]
@saifun is it done?

**Comment by saifun** [comment]
Nice job Shai. 
[LGTM, Approval]
