### ISSUE TITLE
fix repo size

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#49]
your repo is very large, probably due to large binaries that you committed. 
please find a way to erase them in the history. this requires google search and careful actions

**Comment by ofiralexi** [comment]
@yossigil Removed target files. Is the repo size still big?

**Comment by yossigil** [comment]
i am not quite sure you solved it. you should try erase the binary files from the history. this is not trivial...

**Comment by ofiralexi** [comment]
Oh yes the history was a real issue.
I believe it is fixed now - what do you think ? @yossigil

**Comment by yossigil** [comment]
1. what did you do?
2. it is your responsibility to show that the issue was solve

**Comment by ofiralexi** [comment]
I ran bfg(as recommended by git) to remove all traces of .class files, target ,metadata or bin folders
For examle:
![image](https://user-images.githubusercontent.com/37834992/48191343-851c2000-e34d-11e8-9a9a-303d838792e1.png)
Now the .git folder size is only 2MB and not 17MB
![image](https://user-images.githubusercontent.com/37834992/48191386-9d8c3a80-e34d-11e8-9d8d-369b7f249488.png)

**Comment by yossigil** [comment]
good job
