### ISSUE TITLE
fix the project setup to use java level 10 at least. 

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#50]
check out the history of ` .settings/org.eclipse.jdt.core.prefs `

**Comment by Matanpugach** [comment]
@ShaiZeevi @YarinSh @yoavz1997 @ShaiZeevi @ofiralexi @saifun @Itamaror we should all change our compilers to java 10

**Comment by ofiralexi** [comment]
I did 👍

**Comment by Itamaror** [comment]
Did it

**Comment by ShaiZeevi** [comment]
Me too

**Comment by Matanpugach** [comment]
Did it

**Comment by YarinSh** [comment]
Did it

**Comment by yossigil** [comment]
make sure the .setting file is synchronized

**Comment by saifun** [comment]
Done :)

**Comment by yossigil** [comment]
by which commit?

**Comment by yoavz1997** [comment]
This commit changed the .settings/org.eclipse.jdt.core.prefs to the right compliance level

d614a61e20f1f7dc0f58e455e2921188c9bb367f

**Comment by yoavz1997** [comment]
The last commit changed the compliance level to 1.8
3ea7594f0ed2bfe81828af23f1f7eeebc61f89b8

**Comment by yossigil** [comment]
what's up?
