### ISSUE TITLE
fix name of SingletonTest

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#52]
must match to the class being tested

**Comment by ShaiZeevi** [comment]
we did, however right now singletonTest.java as gone as we moved in to an inner class of singleton called TEST
#54

**Comment by ShaiZeevi** [comment]
Done

**Comment by yossigil** [comment]
but is yoav the guy who did the issue?

**Comment by ShaiZeevi** [comment]
He changed the name the first time
