### ISSUE TITLE
Use TDD to develop a function iterables.alternate that takes two iterables, and returns an iterable that returns elements in these in alternating order, until the shortest

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#55]
_From @yossigil on November 8, 2018 10:18_

Use TDD to develop a function iterables.alternate that takes two iterables over elements of the same kind, and returns an iterable that returns elements in these in alternating order, until the shortest one is exhausted, and then continues with the other.

use TDD to design and implement specification for the case that one or both arguments are null.
be sure to break tests before you write any line of code.

_Copied from original issue: TechnionYP5779/team6#60_

**Comment by Itamaror** [comment]
Done.

**Comment by yoavz1997** [comment]
@saifun is it done?

**Comment by saifun** [comment]
Good job @Itamaror 
LGTM, Approval
