### ISSUE TITLE
Mange the Issues' Time Table

### ISSUE THREAD

**Issue by yoavz1997** [TechnionYP5779/team1#56]

**Comment by yossigil** [comment]
not good enough... we talked about this in the lession; dont invent format...
you want use excel to manage your time. better put it in a wiki.

**Comment by yoavz1997** [comment]
It is a Google Sheet rather than excel

**Comment by yossigil** [comment]
Yoav, this is still a NEW FORMAT. please do not introduce new formats of sharing

**Comment by yoavz1997** [comment]
OK, @ShaiZeevi will fix it

**Comment by yossigil** [comment]
thanks

**Comment by saifun** [comment]
Fixed

**Comment by yossigil** [comment]
how was it fixed?

**Comment by yoavz1997** [comment]
It was uploaded to the wiki
https://github.com/TechnionYP5779/team1/wiki/Team-Meeting-%233:-7.11.2018
https://github.com/TechnionYP5779/team1/wiki/Team-Meeting-%234---14.11.2018

**Comment by yossigil** [comment]
thanks
