### ISSUE TITLE
Make sure all closed issues have an assignee

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#57]
_From @yossigil on November 8, 2018 10:48_

each one of you will need to make a report on what he did for the sprint, this report should include all non duplicate issues that he closed.

For this reason, we need to make sure that all duplicates are marked duplicate.

_Copied from original issue: TechnionYP5779/team6#61_

**Comment by ShaiZeevi** [comment]
Done, closing

**Comment by yoavz1997** [comment]
@yoavz1997 make sure?

**Comment by yoavz1997** [comment]
![image](https://user-images.githubusercontent.com/33288016/48474183-aaec6d80-e802-11e8-9f25-cf8b3a31201e.png)
Done
