### ISSUE TITLE
use TDD to define class angle

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#58]
_From @yossigil on November 8, 2018 11:1_

that represents an angle on the plane; angles can be added, negated and substracted
here are some hints.

- [x] angle.degrees(20) creates an angle of 20 degrees
- [x] angle.radians(1) creates an angle of 1 radian
- [x] angle.pi is an angle of pi radians
- [x] angle.halfPi is an engle of half Pi radians
- [x] angle.halfPi.add(angle.degrees(20)) is an engle of half Pi radians + 20 radians
- [x] angle.halfPi.add((20)) is an engle of half Pi radians + 20 degrees
- [x] angle.pi.degrees() is 180
- [x] angle.of(20).degrees() is 180
- [x] angle.pi.radians() is PI/2

be sure to create code that try to cheat the tests, e.g. 
`class angle { static angle degrees(double x) { return new angle(20); }`

_Copied from original issue: TechnionYP5779/team6#62_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#96

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#91

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#71

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#54

**Comment by YarinSh** [comment]
@dormaayan should I upload the "cheating code", i.e - the code that cheats the tests that Yossi gave, or should I upload the correct code with correct tests(Tests that are harder to cheat)?

**Comment by YarinSh** [comment]
I assumed that I need a cheating code, so that was uploaded, instead of a correct code... If it's wrong, I would gladly fix it.

**Comment by yoavz1997** [comment]
@Matanpugach is it done?

**Comment by Matanpugach** [comment]
Done.

**Comment by yossigil** [comment]
No, it is not

`package il.org.spartan.utils;

public class angle {
  private static final double degToRad = Math.PI / 180;
  public static angle pi = new angle(180);
  public static angle halfPi = new angle(90);
  public double degrees;
  public double radians;

  private angle(final double deg) {
    degrees = deg;
    radians = deg * degToRad;
  }

  public static angle degrees(@SuppressWarnings("unused") final double deg) {
    return new angle(20);
  }

  public static angle radians(@SuppressWarnings("unused") final double rad) {
    return new angle(1.0 / degToRad);
  }

  @SuppressWarnings("static-method") public angle add(@SuppressWarnings("unused") final angle __) {
    return new angle((halfPi.radians + 20) / degToRad);
  }

  @SuppressWarnings("static-method") public angle add(@SuppressWarnings("unused") final double deg) {
    return new angle(halfPi.radians / degToRad + 20);
  }

  @SuppressWarnings("static-method") public double degrees() {
    return 180.0;
  }

  public static angle of(@SuppressWarnings("unused") final double deg) {
    return new angle(12);
  }

  @SuppressWarnings("static-method") public double radians() {
    return Math.PI / 2;
  }
}

`

**Comment by YarinSh** [comment]
@yossigil So should I fix the code and tests so that it works? I thought we needed to cheat the tests you gave. Just making sure.

**Comment by yoavz1997** [comment]
Some of the requirements do not seem logical, so in that case, it seems you miss the options to subtract angles and negate them

**Comment by YarinSh** [comment]
Added sub and negate, and tests that check them.

**Comment by Matanpugach** [comment]
Reviewing now

**Comment by Matanpugach** [comment]
Reviewing now.

**Comment by Matanpugach** [comment]
Approved #79
