### ISSUE TITLE
Shai's Issue

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1#6]
Generic non-Issue.
@Matanpugach, @ofiralexi, @yoavz1997, @saifun, @Itamaror, @YarinSh 

" 'Cause I got issues
But you got 'em too
So give 'em all to me
And I'll give mine to you
Bask in the glory
Of all our problems
'Cause we got the kind of love
It takes to solve 'em" (Julia Michaels, 2017)

#2

**Comment by Matanpugach** [comment]
thanks.
