### ISSUE TITLE
make sure all issues, including closed ones, have a milestone

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#60]
to do so, apply searches in the issues tab of github

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#55

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#72

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#93

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#100

**Comment by ShaiZeevi** [comment]
Done, all issues have milestones

![image](https://user-images.githubusercontent.com/36810747/48215384-d0a0ef00-e38a-11e8-94a2-704780285575.png)

**Comment by yoavz1997** [comment]
@saifun do all the issues have milestone?

**Comment by saifun** [comment]
Added missing milestones. Now all the issues have milestones
