### ISSUE TITLE
spartanize

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#62]
Tip: Inline local test_res into subsequent statement	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 221	Inlining
Tip: Remove the curly brackets in the @SuppressWarnings annotation	asTest.java	/fluent.ly/src/test/java/fluent/ly	line 66	SyntacticBaggage
Tip: Rename caught e (Exception) to ¢	idiomaticTest.java	/fluent.ly/src/test/java/fluent/ly	line 24	Centification
Tip: Rewrite 'azzert.assertFalse(anonymous.ly(supFalse))' as assert command	anonymousTest.java	/fluent.ly/src/test/java/fluent/ly	line 12	Idiomatic
Tip: Rewrite 'azzert.assertFalse(Bool.valueOf(false).get())' as assert command	BoolTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 11	Idiomatic
Tip: Rewrite 'azzert.assertFalse(Bool.valueOf(false).set(false).get())' as assert command	BoolTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 30	Idiomatic
Tip: Rewrite 'azzert.assertFalse(Bool.valueOf(true).clear().get())' as assert command	BoolTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 15	Idiomatic
Tip: Rewrite 'azzert.assertFalse(container.includedIn(contained))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 42	Idiomatic
Tip: Rewrite 'azzert.assertFalse(is.in(Integer.valueOf(1),Integer.valueOf(8),Integer.valueOf(100),Integer.valueOf(2)))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 8	Idiomatic
Tip: Rewrite 'azzert.assertFalse(is.intIsIn(1,2,3,4,5,6,7))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 18	Idiomatic
Tip: Rewrite 'azzert.assertFalse(is.out(Integer.valueOf(8),Integer.valueOf(8),Integer.valueOf(100),Integer.valueOf(2)))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 14	Idiomatic
Tip: Rewrite 'azzert.assertFalse(my_statistics.isEmpty())' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 84	Idiomatic
Tip: Rewrite 'azzert.assertFalse(new Bool().get())' as assert command	BoolTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 21	Idiomatic
Tip: Rewrite 'azzert.assertFalse(new Bool(false).get())' as assert command	BoolTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 20	Idiomatic
Tip: Rewrite 'azzert.assertFalse(notEmpty.isEmpty())' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 48	Idiomatic
Tip: Rewrite 'azzert.assertFalse(range.equals(new Object()))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 17	Idiomatic
Tip: Rewrite 'azzert.assertFalse(range.equals(range2))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 18	Idiomatic
Tip: Rewrite 'azzert.assertFalse(range.equals(range3))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 19	Idiomatic
Tip: Rewrite 'azzert.assertFalse(range.equals(range4))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 20	Idiomatic
Tip: Rewrite 'azzert.assertFalse(small.merge(big).equals(incorrect))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 54	Idiomatic
Tip: Rewrite 'azzert.assertTrue(!main.overlapping(new Range(3,4)))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 60	Idiomatic
Tip: Rewrite 'azzert.assertTrue((samplePair + "").equals(Pair.newPair(first,second) + ""))' as assert command	PairTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 26	Idiomatic
Tip: Rewrite 'azzert.assertTrue(¢.next().equals(Integer.valueOf(count)))' as assert command	asTest.java	/fluent.ly/src/test/java/fluent/ly	line 12	Idiomatic
Tip: Rewrite 'azzert.assertTrue(¢.next().equals(Integer.valueOf(count)))' as assert command	asTest.java	/fluent.ly/src/test/java/fluent/ly	line 20	Idiomatic
Tip: Rewrite 'azzert.assertTrue(anonymous.ly(() -> true))' as assert command	anonymousTest.java	/fluent.ly/src/test/java/fluent/ly	line 11	Idiomatic
Tip: Rewrite 'azzert.assertTrue(as.array(Integer.valueOf(1))[0].equals(Integer.valueOf(1)))' as assert command	asTest.java	/fluent.ly/src/test/java/fluent/ly	line 97	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Bool.valueOf(false).set().get())' as assert command	BoolTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 25	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Bool.valueOf(false).set(true).get())' as assert command	BoolTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 29	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Bool.valueOf(true).get())' as assert command	BoolTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 10	Idiomatic
Tip: Rewrite 'azzert.assertTrue(contained.includedIn(container))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 41	Idiomatic
Tip: Rewrite 'azzert.assertTrue(firstVariance >= 13 && firstVariance <= 14)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 72	Idiomatic
Tip: Rewrite 'azzert.assertTrue(idiomatic.take(this) != null)' as assert command	idiomaticTest.java	/fluent.ly/src/test/java/fluent/ly	line 111	Idiomatic
Tip: Rewrite 'azzert.assertTrue(idiomatic.unless(false).eval(() -> new Object()) != null)' as assert command	idiomaticTest.java	/fluent.ly/src/test/java/fluent/ly	line 94	Idiomatic
Tip: Rewrite 'azzert.assertTrue(idiomatic.when(true).eval(() -> new Object()) != null)' as assert command	idiomaticTest.java	/fluent.ly/src/test/java/fluent/ly	line 103	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Int.valueOf(i).inner().equals(Integer.valueOf(i)))' as assert command	IntTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 12	Idiomatic
Tip: Rewrite 'azzert.assertTrue(int1.inner().equals(Integer.valueOf(i + 1)))' as assert command	IntTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 19	Idiomatic
Tip: Rewrite 'azzert.assertTrue(int1.inner().equals(Integer.valueOf(i1 + i2)))' as assert command	IntTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 27	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Integer.valueOf(1).equals(as.iterator(Integer.valueOf(1)).next()))' as assert command	asTest.java	/fluent.ly/src/test/java/fluent/ly	line 93	Idiomatic
Tip: Rewrite 'azzert.assertTrue(is.empty(""))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 30	Idiomatic
Tip: Rewrite 'azzert.assertTrue(is.empty((ArrayList<Integer>)null))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 42	Idiomatic
Tip: Rewrite 'azzert.assertTrue(is.empty((Integer[])null))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 34	Idiomatic
Tip: Rewrite 'azzert.assertTrue(is.empty((String)null))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 26	Idiomatic
Tip: Rewrite 'azzert.assertTrue(is.empty(new ArrayList<Integer>()))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 46	Idiomatic
Tip: Rewrite 'azzert.assertTrue(is.empty(new Integer[0]))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 38	Idiomatic
Tip: Rewrite 'azzert.assertTrue(is.in(Integer.valueOf(8),Integer.valueOf(8),Integer.valueOf(100),Integer.valueOf(2)))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 13	Idiomatic
Tip: Rewrite 'azzert.assertTrue(is.intIsIn(5,5,6,7,8,9))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 22	Idiomatic
Tip: Rewrite 'azzert.assertTrue(is.out(Integer.valueOf(1),Integer.valueOf(8),Integer.valueOf(100),Integer.valueOf(2)))' as assert command	isTest.java	/fluent.ly/src/test/java/fluent/ly	line 9	Idiomatic
Tip: Rewrite 'azzert.assertTrue(mad3 >= 1 && mad3 <= 2)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 45	Idiomatic
Tip: Rewrite 'azzert.assertTrue(main.overlapping(comingFromLeft))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 61	Idiomatic
Tip: Rewrite 'azzert.assertTrue(main.overlapping(comingFromRight))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 62	Idiomatic
Tip: Rewrite 'azzert.assertTrue(main.overlapping(container))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 63	Idiomatic
Tip: Rewrite 'azzert.assertTrue(main.overlapping(unrelated))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 64	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.isEmpty())' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 80	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.isEmpty())' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 88	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.max() == 15)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 105	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.mean() == first_mean)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 120	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.mean() == second_mean)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 124	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.mean() == third_mean)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 129	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.min() == 15)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 144	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.missing() == 0)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 148	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.missing() == missing_value)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 153	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.n == 0)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 157	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.n == nth_value)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 162	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.sd() == 2)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 171	Idiomatic
Tip: Rewrite 'azzert.assertTrue(my_statistics.variance() == 4)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 190	Idiomatic
Tip: Rewrite 'azzert.assertTrue(new Bool(true).get())' as assert command	BoolTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 19	Idiomatic
Tip: Rewrite 'azzert.assertTrue(new Range(2,2).isEmpty())' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 47	Idiomatic
Tip: Rewrite 'azzert.assertTrue(new Storer<>(Integer.valueOf(5)) != null)' as assert command	idiomaticTest.java	/fluent.ly/src/test/java/fluent/ly	line 98	Idiomatic
Tip: Rewrite 'azzert.assertTrue(new Storer<>(this) != null)' as assert command	idiomaticTest.java	/fluent.ly/src/test/java/fluent/ly	line 86	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Pair.makePairs(5,5).length == 25)' as assert command	PairTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 34	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Pair.makePairs(5).length == 5)' as assert command	PairTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 30	Idiomatic
Tip: Rewrite 'azzert.assertTrue(range.equals(copy))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 22	Idiomatic
Tip: Rewrite 'azzert.assertTrue(range.equals(equal))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 21	Idiomatic
Tip: Rewrite 'azzert.assertTrue(samplePair.equals(Pair.newPair(first,second)))' as assert command	PairTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 25	Idiomatic
Tip: Rewrite 'azzert.assertTrue(samplePair.hashCode() == Pair.newPair(first,second).hashCode())' as assert command	PairTest.java	/fluent.ly/src/test/java/il/org/spartan/utils	line 24	Idiomatic
Tip: Rewrite 'azzert.assertTrue(small.merge(big).equals(new Range(2,8)))' as assert command	RangeTest.java	/fluent.ly/src/test/java/fluent/ly	line 53	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Statistics.mad(second_integer_sample) == 0)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 41	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Statistics.median(first_integers_sample) == 16.0)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 50	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Statistics.median(second_integer_sample) == second_median)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 52	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Statistics.median(third_integer_sample) == third_median)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 54	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Statistics.sampleMean(first_integers_sample) == first_mean)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 62	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Statistics.sampleMean(second_integer_sample) == second_mean)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 64	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Statistics.sampleMean(third_integer_sample) == third_mean)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 66	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Statistics.sampleVariance(second_integer_sample) == second_variance)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 74	Idiomatic
Tip: Rewrite 'azzert.assertTrue(Statistics.sampleVariance(third_integer_sample) == third_variance)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 76	Idiomatic
Tip: Rewrite 'azzert.assertTrue(sto.get().booleanValue())' as assert command	idiomaticTest.java	/fluent.ly/src/test/java/fluent/ly	line 63	Idiomatic
Tip: Rewrite 'azzert.assertTrue(sto.unless(false).booleanValue())' as assert command	idiomaticTest.java	/fluent.ly/src/test/java/fluent/ly	line 67	Idiomatic
Tip: Rewrite 'azzert.assertTrue(sto.when(true).booleanValue())' as assert command	idiomaticTest.java	/fluent.ly/src/test/java/fluent/ly	line 65	Idiomatic
Tip: Rewrite 'azzert.assertTrue(test_res == 5)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 222	Idiomatic
Tip: Rewrite 'azzert.assertTrue(true)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 99	Idiomatic
Tip: Rewrite 'azzert.assertTrue(true)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 114	Idiomatic
Tip: Rewrite 'azzert.assertTrue(true)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 138	Idiomatic
Tip: Rewrite 'azzert.assertTrue(true)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 201	Idiomatic
Tip: Rewrite 'azzert.assertTrue(true)' as assert command	statisticsTest.java	/fluent.ly/src/test/java/il/org/spartan/statistics	line 208	Idiomatic
Tip: Rewrite 'azzert.assertTrue(x.contains(Integer.valueOf(1)))' as assert command	asTest.java	/fluent.ly/src/test/java/fluent/ly	line 61	Idiomatic
Tip: Rewrite 'azzert.assertTrue(x.contains(Integer.valueOf(2)))' as assert command	asTest.java	/fluent.ly/src/test/java/fluent/ly	line 62	Idiomatic
Tip: Rewrite 'azzert.assertTrue(x.contains(Integer.valueOf(2)))' as assert command	asTest.java	/fluent.ly/src/test/java/fluent/ly	line 69	Idiomatic
Tip: Rewrite 'azzert.assertTrue(x.contains(Integer.valueOf(3)))' as assert command	asTest.java	/fluent.ly/src/test/java/fluent/ly	line 63	Idiomatic
Tip: Rewrite 'azzert.assertTrue(x.contains(Integer.valueOf(3)))' as assert command	asTest.java	/fluent.ly/src/test/java/fluent/ly	line 70	Idiomatic
Tip: Use 1L*tested instead of (long)tested	unboxTest.java	/fluent.ly/src/test/java/fluent/ly	line 190	Nanopatterns

**Comment by YarinSh** [comment]
@yossigil Just to make sure, should I change this
![image](https://user-images.githubusercontent.com/32907017/48218599-e7e3da80-e392-11e8-94c2-2761c025b555.png)
to this:
![image](https://user-images.githubusercontent.com/32907017/48218622-f92ce700-e392-11e8-90ac-ca443cc54253.png)

It removes the tip, but then, we use an assert that is not part of the azzert class, is it OK?

**Comment by yossigil** [comment]
yes, it is ok

**Comment by yossigil** [comment]
ain't this issue a duplicate? if it is mark it as one...

**Comment by YarinSh** [comment]
Duplicate #37
