### ISSUE TITLE
Fix 2 failed Tests

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1#65]
Description : in src/test/fluent/ly/SeparateTest
the two following functions 
- [x]  byIntArrayChar()
- [x]  byIntArrayString()
fails upon moving the TEST inner class to package related class.
To do: fix the failed test

**Comment by yoavz1997** [comment]
All the tests in the /src/test/java pass #79 
![image](https://user-images.githubusercontent.com/33288016/48483389-ff501700-e81b-11e8-9337-b73699b3c387.png)
