### ISSUE TITLE
Search for databases for the TechnoBot

### ISSUE THREAD

**Issue by saifun** [TechnionYP5779/team1#69]
We are searching for data bases where the bot can gather information from

**Comment by yoavz1997** [comment]
Regarding the first feature:
The Webcourse has a section called "Assignments" in which the due dates of each homework is written.
In the moodle, the submission page has a specific URL "/mod/assign" or "/mod/workshop". Using page crawling we can extract the due dates of homework and display them.

**Comment by yoavz1997** [comment]
Regarding the third feature:
In order to set reminders to register to courses, we can ask the users for their credentials and parse the URL
https://ug3.technion.ac.il/rishum/register-date

**Comment by saifun** [comment]
Regarding feature 5 - emails and phones
We can parse the various faculties websites. For example: http://www.cs.technion.ac.il/

**Comment by yoavz1997** [comment]
A wiki page was uploaded https://github.com/TechnionYP5779/team1/wiki/Finding-Data-Bases

**Comment by yossigil** [comment]
page is empty; reopening

**Comment by yoavz1997** [comment]
Wrong url https://github.com/TechnionYP5779/team1/wiki/Finding-DataBases
