### ISSUE TITLE
consolidate function unused into interface forget

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team1#75]
_From @yossigil on November 14, 2018 9:14_

they do the same; refactor the code accordingly

_Copied from original issue: TechnionYP5779/team6#80_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#120

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#105

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#78

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#60

**Comment by yossigil** [comment]
see comment on closing commit

**Comment by ofiralexi** [comment]
please review Yossis comment and then move it to review needed again.

**Comment by ShaiZeevi** [comment]
![image](https://user-images.githubusercontent.com/36810747/48651610-59133580-ea04-11e8-8a55-38a314238c00.png)

Function unused is indeed gone, approved!
