### ISSUE TITLE
Document a push procedure in a wiki page

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team1#77]
_From @yossigil on November 14, 2018 9:11_

Should include formatting, cleanup, tests, spartanization etc.

_Copied from original issue: TechnionYP5779/team6#78_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#122

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#107

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#80

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#62

**Comment by saifun** [comment]
Done! 
https://github.com/TechnionYP5779/team1/wiki/Code-Submission-Procedure

**Comment by yossigil** [comment]
add a comment to reformat the code

**Comment by saifun** [comment]
By ‘reformatting’ - do you mean something else than spartanizing? @yossigil

**Comment by saifun** [comment]
Added. 
I also added a comment about code review
