### ISSUE TITLE
Consolidate classes Range and range

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team1#78]
_From @yossigil on November 14, 2018 9:9_

if you created class Range (capitalized).

The correct design should  have three (internal?) classes,
one for infinite range bounded above,
another for infinite bounded below
and a third for a finite range.

for example,
range.to(3).to(2) generates an error,
range.to(3).from(2) creates a finite range,

the person responsible for this should not be the person who wrote class Range

_Copied from original issue: TechnionYP5779/team6#77_

**Comment by Matanpugach** [comment]
I wrote range. Will Consolidate classes Range and range into range

**Comment by yossigil** [comment]
hint, you need three different classes, for the three kinds of ranges, each supporting different functions

**Comment by ShaiZeevi** [comment]
@Matanpugach could you please list the changes and explain the consolidation of the two classes. Most of us haven’t seen both of them and I want to review it and make sure it’s ok

**Comment by ShaiZeevi** [comment]
Please change the name of RangeTest to match the convention (<className> + "Test"), after that you can close the issue

**Comment by Matanpugach** [comment]
@ShaiZeevi Done! Thanks!
