### ISSUE TITLE
refactor the code so that it uses box and unbox 

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team1#80]
_From @yossigil on November 14, 2018 9:17_

code should not include e.g., `x.intValue` or `Short.valueOf(3)`, except for in class box and class unbox

_Copied from original issue: TechnionYP5779/team6#81_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#125

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#110

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#83

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#65

**Comment by ShaiZeevi** [comment]
Note: I'm leaving the use of valueOf for the purpose of string conversion
![image](https://user-images.githubusercontent.com/36810747/48476251-37009400-e807-11e8-9c3f-5c4d25d40c65.png)

**Comment by ShaiZeevi** [comment]
@ofiralexi 
Can you review the changes?

**Comment by yossigil** [comment]
good progress

**Comment by saifun** [comment]
Nice job @ShaiZeevi

**Comment by yossigil** [comment]
e.g.,
`        @Override public Integer next() {
          if (!hasNext())
            throw new NoSuchElementException();
          final int $ = current;
          current += delta;
          return box.box($);
        }
`
fix to
         return box.it($);

**Comment by ShaiZeevi** [comment]
Understood, I'll make sure of it

**Comment by yoavz1997** [comment]
Why is it closed?

**Comment by ShaiZeevi** [comment]
I believe this issue is completed. I reopened #141 instead
