### ISSUE TITLE
Test runs should be with assertions enabled

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team1#81]
_From @yossigil on November 14, 2018 9:21_

Play with eclipse, it is better to write
`assert x`
then
`azzert.isTrue(x)`

but when you run tests the jvm should have assertions enabled

_Copied from original issue: TechnionYP5779/team6#82_

**Comment by ofiralexi** [comment]
![image](https://user-images.githubusercontent.com/37834992/48474237-cb1c2c80-e802-11e8-85a7-ac210f047ac3.png)

**Comment by yossigil** [comment]
You should use a jvm flag. Can you please show where this flag is set? use screen dump if necessary

**Comment by ofiralexi** [comment]
As you can see the assertion flag is enabled for my eclipse:
![image](https://user-images.githubusercontent.com/37834992/48542373-b05fbb80-e8c7-11e8-82b1-dd7706374683.png)

**Comment by yoavz1997** [comment]
Done #79
