### ISSUE TITLE
  @SuppressWarnings("boxing")

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#85]
_From @yossigil on November 14, 2018 11:9_

This should never occur in the code, perhaps with the exception of class "box"
Use class box, and/or box.it() instead.

Only close this issue with a screen dump showing search for   @SuppressWarnings("boxing")

_Copied from original issue: TechnionYP5779/team6#87_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#129

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#114

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#90

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#69

**Comment by ShaiZeevi** [comment]
There aren't any

![image](https://user-images.githubusercontent.com/36810747/48484605-3b38ab80-e81f-11e8-8618-9e738dc5db47.png)

![image](https://user-images.githubusercontent.com/36810747/48484665-5d322e00-e81f-11e8-991a-89705e9c5a11.png)

**Comment by yoavz1997** [comment]
![image](https://user-images.githubusercontent.com/33288016/48490291-c882fc80-e82d-11e8-95ab-d98e9d5d66a9.png)
It seems that it slipped through the search because it has a few SuppressWarnings together

**Comment by ShaiZeevi** [comment]
Thanks. I'll fix it today

**Comment by ShaiZeevi** [comment]
Many uses of unbox end up resulting in a null conversion warning. How should I take care of this?

e.g:
![image](https://user-images.githubusercontent.com/36810747/48546319-bdcd7380-e8d0-11e8-9d2f-89534f105bec.png)
Because supposedly, these two elements might be null

**Comment by yossigil** [comment]
fix the interface unbox so that it returns zero in case of null...

**Comment by ShaiZeevi** [comment]
Will do, thanks

**Comment by ShaiZeevi** [comment]
These are the only refs:
![image](https://user-images.githubusercontent.com/36810747/48554180-59b5aa00-e8e6-11e8-8271-cbe82be459a8.png)
I searched for the string "boxing" in all files no I'm pretty sure none were missed
