### ISSUE TITLE
@SuppressWarning of "static-method"

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#86]
_From @yossigil on November 14, 2018 10:54_

If a unit test class does not use fixtures, all its methods would get "static-method" warning. Make sure that that in all unit tests like this, "static-method"  warning is suppressed in the class definition.

Do look up "fixtures" and read about junit 

_Copied from original issue: TechnionYP5779/team6#86_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#130

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#115

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#91

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#70

**Comment by ShaiZeevi** [comment]
@Matanpugach 
Looks good?

**Comment by yoavz1997** [comment]
I reviewed it, and there are no @SuppressWarnings("static-method") on functions

**Comment by yossigil** [comment]
good job
