### ISSUE TITLE
Create a cleanup profile for eclipse, and save it with your project

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#87]
_From @yossigil on November 14, 2018 11:21_

Connect this profile with the wiki you created for a commit procedure

![image](https://user-images.githubusercontent.com/12775400/48479501-315b7c00-e810-11e8-997e-c2a63792c609.png)

_Copied from original issue: TechnionYP5779/team6#88_

**Comment by YarinSh** [comment]
@yossigil 
I have created the profile, and even exported it.
- Should I push the exported xml profile?
- Should I cleanup the code?
- And what do you mean by 'Connect this profile with the wiki'? We have a pull procedure, should I write there that the cleanup needs to be applied before committing and pushing?

**Comment by YarinSh** [comment]
Uploaded the cleanup profile and added to the [wiki](https://github.com/TechnionYP5779/team1/wiki/Importing-Cleanup-Profile).

**Comment by Matanpugach** [comment]
Reviewed now. Closing. #79
