### ISSUE TITLE
Saifun Naveh - schedule for the semester

### ISSUE THREAD

**Issue by saifun** [TechnionYP5779/team1#9]
Please choose a week where you are offline and edit the schedule properly in the wiki page
@ofiralexi @yoavz1997 @ShaiZeevi @Matanpugach @YarinSh @Itamaror

**Comment by ofiralexi** [comment]
Done

**Comment by Matanpugach** [comment]
Done.

**Comment by yoavz1997** [comment]
Added myself

**Comment by ShaiZeevi** [comment]
Done

**Comment by YarinSh** [comment]
Done

**Comment by Itamaror** [comment]
Done

**Comment by ofiralexi** [comment]
Great ! All done closing the issue :)
