### ISSUE TITLE
Convert azzert.that(X, is(true)) to assert x

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#90]
_From @yossigil on November 14, 2018 20:39_

Similalry, convert azzert.that(X, is(false)) to assert !x
Similalry, convert azzert.thattrue, is(Boolean.FALSE)) to assert !x,
etc.

_Copied from original issue: TechnionYP5779/team6#90_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#133

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#119

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#93

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#75

**Comment by Matanpugach** [comment]
@yoavz1997 The only apperance was. 
![image](https://user-images.githubusercontent.com/27849930/48708954-b1b51f00-ec0c-11e8-9b48-9a408343f681.png)

**Comment by yoavz1997** [comment]
Great, so fix it and tag it as "needs review"

**Comment by Matanpugach** [comment]
@yoavz1997 note that there it is not as simple as the title and is based on internal implementation. I changed it to decrease code duplication.

**Comment by yoavz1997** [comment]
Ok, in this case submit it to review

**Comment by Matanpugach** [comment]
@yoavz1997 it is.

**Comment by ShaiZeevi** [comment]
![image](https://user-images.githubusercontent.com/36810747/48719252-b5a16b00-ec25-11e8-9199-a46565bdd7e1.png)
![image](https://user-images.githubusercontent.com/36810747/48719269-bf2ad300-ec25-11e8-8215-53735bf76022.png)

I would say that counts as a success, good job @Matanpugach.
Approved!

**Comment by ShaiZeevi** [comment]
It appears I spoke too soon. Please fix the remaining appearances:
azzert.that(..., is(Boolean.FALSE))
azzert.that(..., is(Boolean.TRUE))

**Comment by ShaiZeevi** [comment]
I noticed usage of azzert.that(..., is(Boolean.FALSE)) and azzert.that(..., is(Boolean.TRUE)) on BoolTest.
Did you leave those on purpose? Or do you think they should be fixed? Please come back to me with an answer

**Comment by yoavz1997** [comment]
![image](https://user-images.githubusercontent.com/33288016/48779341-11c8c580-ece0-11e8-84bc-0a5b595f8c9e.png)
There are still "is(Boolean...)

**Comment by yoavz1997** [comment]
I see that the conversion to assert is not as straightforward as I thought #79
