### ISSUE TITLE
Expand Unit Test For iterables

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1#95]
We want to increase coverage of main, so we need to expand coverage of iterableTest

**Comment by ofiralexi** [comment]
for updating coverage as mentioned in issue #96

**Comment by ShaiZeevi** [comment]
You can't close without a review

**Comment by yoavz1997** [comment]
fixed the boxing warnings as part of #88 
There are some methods which are not covered and some branches as well

**Comment by ofiralexi** [comment]
Yes I see what you mean.
Added more checks - what do you think  ? :)

**Comment by yoavz1997** [comment]
Done #79
