### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1#96]
Description: make a unit test for:
- [x] CSV.java
- [x] Utils.java
- [x] PureIterable.java
- [x] tide.java
- [x] English.java
- [x]  out.java
- [x]  nulling.java
- [x]  iterables.java
- [x]  safe.java
- [x]  Table.java
- [x]  TableRenderer.java
- [x] Row.java
- [x] note.java
- [x] the.java
- [x] __.java
- [x] list.java
- [x] robust.java
- [x] has.java
- [x] lazy.java
- [x] defaults.java
- [x] not.java & yes.java ( very short classes )
- [x] Str.java
-------------------------------------
make sure the CLASS coverage is at least 60%
-------------------------------------
Each one please choose classes to take on their unit tests
open relevant issues and referance this one
put the unit-test milestone as the milestone
mark check next to the classes that you've decided to test

**Comment by Matanpugach** [comment]
i took utils,java, has

**Comment by ShaiZeevi** [comment]
I have nulling, default, lazy

**Comment by ofiralexi** [comment]
I took Utils, yes & no , iterables

**Comment by Matanpugach** [comment]
@ofiralexi i already took utils

**Comment by YarinSh** [comment]
Took:
PureIterable.java
ImmutableStatistics.java
English.java

**Comment by saifun** [comment]
I assigned:
Note.java
Row.java
robust.java

**Comment by yossigil** [comment]
good job

**Comment by ShaiZeevi** [comment]
I'm pretty sure you meant defaults.java and not default, I'm changing it

**Comment by yoavz1997** [comment]
Left with TableRenderer.java, __.java and has.java

**Comment by ofiralexi** [comment]
apparenately yes and not are really quick and didn't contributed anything to the coverage
Covering str.java also instead

**Comment by YarinSh** [comment]
ImmutableStatistics requires classes that are not in the code, to test it, hence I have switched it to tide.java.

**Comment by ShaiZeevi** [comment]
Any other classes need to be tested? I could do with one more

**Comment by Matanpugach** [comment]
@ShaiZeevi it's best to wait until all tests are complete, so the division will be even

**Comment by Matanpugach** [comment]
Good job all! I think the purpose of this issue - test assignment, is now over. If we shall decide to test further, please reopen this. Closing.
