### ISSUE TITLE
Unit Test for Yes & No

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1#98]
Description : unit tests for classes as mentioned in #96

**Comment by ShaiZeevi** [comment]
You can't close without a review

**Comment by yoavz1997** [comment]
The name of "YesTest" does not match the class "yes"
Could not find "noTest"

**Comment by ofiralexi** [comment]
I meant NotTest. There was a typo there @yoavz1997 can you look at this as well ?

**Comment by ofiralexi** [comment]
Changed classes names
The coverage is 100 and 85 precent
![image](https://user-images.githubusercontent.com/37834992/48633489-19305c00-e9cc-11e8-97b7-3c13ea63dc6f.png)

![image](https://user-images.githubusercontent.com/37834992/48633467-0c136d00-e9cc-11e8-8057-881bdbd65046.png)

**Comment by yoavz1997** [comment]
The last branch of not seems to be achievable, please add it

**Comment by yoavz1997** [comment]
Done #79
